# Error: Matter.SentenceSpacing
#
# Checks for incorrect spacing (no spaces, or more than one space) around punctuation.
#
# For a list of all options, see https://vale.sh/docs/topics/styles/
extends: existence
message: "Remove the extra space: '%s'"
level: error
nonword: true
tokens:
  - '[a-z][.?!,][A-Z]'
  - '[\w.?!,\(\)\-":] {2,}[\w.?!,\(\)\-":]'
