name: Vale

on:
  pull_request:

jobs:
  vale:
    name: Lint Source
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Vale Linter
        uses: errata-ai/vale-action@v2.1.0
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          version: 3.12.0
          files: src/
          fail_on_error: true
